Repository clibs/clib, pull requests merged in 2020-07, with the labels that each got.

#187 Add support for "clib i"
  src/clib.c
Labels: 1.0, enhancement

#180 clib@next
  .github/workflows/tests.yml
  .gitignore
  Makefile
  Readme.md
  clib.json
  deps/clib-cache/package.json
  deps/clib-package/clib-package.c
  deps/clib-package/clib-package.h
  deps/clib-package/clib.json
  deps/clib-package/package.json
  deps/commander/clib.json
  deps/hash/clib.json
  deps/hash/hash.c
  deps/hash/hash.h
  deps/hash/khash.h
  deps/hash/package.json
  deps/http-get/clib.json
  deps/http-get/http-get.c
  deps/http-get/http-get.h
  deps/list/package.json
  deps/logger/clib.json
  deps/parson/clib.json
  deps/str-concat/clib.json
  deps/strdup/package.json
  deps/which/clib.json
  deps/wildcardcmp/clib.json
  package.json
  src/clib-build.c
  src/clib-configure.c
  src/clib-init.c
  src/clib-install.c
  src/clib-search.c
  src/clib.c
  src/version.h
  test.sh
  test/install-binary-dependencies.sh
Labels: 2.x, next

#194 fix(): capital -V version switch
  Readme.md
  src/clib.c
Labels: 2.x, bug
